[build]
  # Wir konfigurieren Netlify so, dass Serverless Functions aus dem
  # Projektstammverzeichnis gelesen werden. Dadurch ist kein
  # Unterordner "netlify/functions" erforderlich und die Datei
  # chatgpt.js im Root wird als Funktion erkannt. Die restlichen
  # Frontend‑Assets liegen ebenfalls im Stammverzeichnis.
  functions = "./"
  publish = "./"

[functions]
  node_bundler = "esbuild"